package com.lea.kumiko.midware.others.JsPackage;

import java.io.IOException;

public class LayerJs {

    public static final String layerJs = "src/main/webapp/WEB-INF/addressBook/myTeacher/editMyTeacher.jsp                     /addressBook/toEditMyTeacher.do\n" +
            "src/main/webapp/WEB-INF/V2/voip/workPhoneCallHistoryPage.jsp                                    /voip/voipInfo/getWorkPhoneCallHistoryPage.do\n" +
            "src/main/webapp/WEB-INF/customer/fourinone/customerCommunicateHistoryListV2.jsp                         /customerFourInOne/getCustomerCommunicateHistoryPage.do\n" +
            "src/main/webapp/WEB-INF/V2/bigBackstageSales/performanceTarget.jsp                                                  /bigBackstageSales/toPerformanceTarget.do\n" +
            "src/main/webapp/WEB-INF/addressBook/myTeacher/editMyTeacher.jsp                                             /addressBook/toEditMyTeacher.do\n" +
            "src/main/webapp/WEB-INF/V2/courseContentPackage/addSelfDefineCourseContentPackage.jsp       /tra/courseContentPackage/toAddSelfDefineCourseContentPackage.do\n" +
            "src/main/webapp/WEB-INF/V2/courseContentPackage/addSelfDefineCourseContentPackage.jsp  /tra/courseContentPackage/toEditSelfDefineContentPackage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/customerReport/customerStatus/toTaCustomerStatusList.jsp                        /customerReport/customerStatus/toTaCustomerStatusList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/customerReport/customerStatus/toTadCustomerStatusList.jsp                           /customerReport/customerStatus/toTadCustomerStatusList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/customerReport/customerStatus/toTamCustomerStatusList.jsp                       /customerReport/customerStatus/toTamCustomerStatusList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/customerReport/customerStatus/toTamCustomerStatusList.jsp  /customerReport/customerStatus/toViewTamCustomerStatusList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/leads/leadsManage.jsp                  K20181127 废弃使用\n" +
            "src/main/webapp/WEB-INF/addressBook/leads/createLeads.jsp                           无\n" +
            "src/main/webapp/WEB-INF/customer/mycustomer/CrCustomerManage.jsp                            無\n" +
            "src/main/webapp/WEB-INF/cr/mycustomer/crAddCommunicate.jsp                                  /customer/toAddCommunicate.do\n" +
            "src/main/webapp/WEB-INF/customer/mycustomer/customerOptions.jsp                             /customer/customerOptions.do\n" +
            "src/main/webapp/WEB-INF/customer/customerInfoMaintain/addCommunicate.jsp                     /customer/toAddCommunicate.do\n" +
            "src/main/webapp/WEB-INF/customer/customerInfoMaintain/editFollowUpTime.jsp              /customer/toChangeNextContacTime.do\n" +
            "src/main/webapp/WEB-INF/customer/customerInfoMaintain/addCommunicate.jsp                /customer/toAddCommunicate.do\n" +
            "src/main/webapp/WEB-INF/customer/miningPotentialUsers/miningPotentialUsersList.jsp              /miningPotentialUsers/toMiningPotentialUsersList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/customerReport/customerStatus/toViewTaCustomerList.jsp                              /customerReport/customerStatus/toViewTa.do\n" +
            "src/main/webapp/WEB-INF/customer/mycustomer/studyConsultantCustomerManage.jsp                               /studyConsultantCustomer/toMyCustomerManage.do\n" +
            "src/main/webapp/WEB-INF/crAssistantCustomer/addBindCustomer.jsp                                     /crAssistantCustomer/crAddCustomer.do\n" +
            "src/main/webapp/WEB-INF/customer/mycustomer/myCustomerManageV2.jsp                                      /customer/toCrCustomerManage.do\n" +
            "src/main/webapp/WEB-INF/customer/mycustomer/myFastFollowCustomerManage.jsp                              /fastFollowCustomer/toFastFollowCustomerManager.do\n" +
            "src/main/webapp/WEB-INF/customer/mycustomer/myCustomerManageV2.jsp                                  /customer/toCrCustomerManage.do\n" +
            "src/main/webapp/WEB-INF/customer/readingCustomer/readingCustomerList.jsp                /readingCustomer/toReadingCustomerList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/preSetRenewPrice.jsp                                        /addressBook/toSetRenewPrice.do\n" +
            "src/main/webapp/WEB-INF/addressBook/studentInfoMaintain/checkStudentInfoMaintain.jsp                        /addressBook/toStudentInfoMaintain.do\n" +
            "src/main/webapp/WEB-INF/addressBook/studentInfoMaintain/checkStudentInfoMaintain.jsp    /addressBook/toStudentInfoMaintain.do\n" +
            "src/main/webapp/WEB-INF/addressBook/studentInfoMaintain/studentInfoMaintain.jsp                         /addressBook/toStudentInfoMaintain.do\n" +
            "src/main/webapp/WEB-INF/addressBook/myTeacher/editCourseContentPrice.jsp                                /addressBook/toEditCourseContentPrice.do\n" +
            "src/main/webapp/WEB-INF/addressBook/myTeacher/myTeacherManager.jsp                                                       /addressBook/toAddressBook.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonFormalVideoManage.jsp              /addressBook/liveLesson/moreLiveLessonVideoManage.do\n" +
            "src/main/webapp/WEB-INF/V2/trialLecture/teachingTask/teachingTaskList.jsp               /trialLecture/teachingTask/queryTeachingTask.do\n" +
            "src/main/webapp/WEB-INF/V2/trialLecture/teachingTask/teachingTaskManager.jsp            /trialLecture/teachingTask/toTeachingTaskManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/lectureAuditManager.jsp               /addressBook/lectureAudit/addressBook/lectureinvite/lectureAuditManager.jsp\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/lectureInviteManager.jsp          /addressBook/lectureInvite/toLectureInviteManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/searchLectureAuditList.jsp            /addressBook/lectureAudit/queryLectureAuditList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/searchLectureInviteList.jsp           /addressBook/lectureInvite/queryLectureInviteList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonFormalVideoList.jsp            /addressBook/liveLesson/qingQing_formalLiveLessonVideoLimitList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonFormalVideoList.jsp  /addressBook/liveLesson/qingQing_liveLessonMoreVideoList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonUnFormalVideoList.jsp          /addressBook/liveLesson/qingQing_unFormalLiveLessonVideoLimitList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonUnFormalVideoList.jsp  /addressBook/liveLesson/qingQing_liveLessonMoreVideoList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonUnFormalVideoManage.jsp            /addressBook/liveLesson/moreUnLiveLessonVideoManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonVideoList.jsp              /addressBook/liveLesson/qingQing_liveLessonVideoList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonVideoList.jsp /addressBook/liveLesson/qingQing_liveLessonVideoLimitList.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonVideoManage.jsp                /addressBook/liveLesson/liveLessonVideoManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/addLiveClassOrderManager.jsp      /addressBook/onlineGroupLesson/toPlaceOrder.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/allOnlineGroupLesson.jsp          /addressBook/onlineGroupLesson/allOnlineGroupLesson.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/createOnlineGroupLesson.jsp           /addressBook/onlineGroupLesson/createOnlineGroupLesson.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/livecloudLessonManager.jsp        /addressBook/onlineGroupLesson/toLiveCloudLessonManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/modifyPublishCity.jsp             /addressBook/onlineGroupLesson/toModifyPublishCity.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/myOnlineGroupLessonManage.jsp     /addressBook/onlineGroupLesson/myOnlineGroupLessonManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/onlineGroupLessonInfo.jsp         /addressBook/onlineGroupLesson/toOnlineGroupLessonInfo.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/searchOnlineGroupLessonList.jsp               /addressBook/onlineGroupLesson/myOnlineGroupLesson.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/searchOnlineGroupLessonList.jsp /addressBook/onlineGroupLesson/searchOnlineGroupLesson.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/searchOnlineGroupLessonList.jsp  /addressBook/onlineGroupLesson/searchMyOnlineGroupLesson.do\n" +
            "src/main/webapp/WEB-INF/addressBook/teachingtask/teachingTaskList.jsp                                   无\n" +
            "src/main/webapp/WEB-INF/addressBook/teachingtask/teachingTaskManager.jsp                                无\n" +
            "src/main/webapp/WEB-INF/order/cancelOrderConfirm.jsp                            /liveClass/confirmCancelOrder.do\n" +
            "src/main/webapp/WEB-INF/order/cancelOrderConfirm.jsp    /groupOrder/confirmCancelOrder.do\n" +
            "src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp                    /addressBook/toStudentPoolAddOrderV2.do\n" +
            "src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp  /addressBook/toBindedStudentAddOrderV2.do\n" +
            "src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp  /addressBook/toBindedStudentAddOrder.do\n" +
            "src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp  /addressBook/studentPoolV2/toStudentPoolAddOrder.do\n" +
            "src/main/webapp/WEB-INF/order/groupOrderInfoDetail.jsp                      /groupOrder/queryOrderDetail.do\n" +
            "src/main/webapp/WEB-INF/traStat/batchDealTeacherBindingApply.jsp            /tamanager/relation/toBatchDealTeacherBindingApply.do\n" +
            "src/main/webapp/WEB-INF/V2/payment/paymentDetail.jsp                /payment/paymentDetail.do\n" +
            "src/main/webapp/WEB-INF/V2/payment/paymentConfirm.jsp                   /payment/toPaymentConfirm.do\n" +
            "src/main/webapp/WEB-INF/tamanager/assistantBatchApplyChangebindingConfirm.jsp                       /tamanager/student/toBatchChangebindingApplyConfirm.do\n" +
            "src/main/webapp/WEB-INF/tamanager/assistantApplyChangebindingConfirm.jsp                                    /tamanager/student/toChangebindingApplyConfirm.do\n" +
            "src/main/webapp/WEB-INF/tamanager/batchDealTeacherBindingApply.jsp                                          无\n" +
            "src/main/webapp/WEB-INF/V2/performance/performanceManage.jsp                /accountBook/performance/queryPerformance.do\n" +
            "src/main/webapp/WEB-INF/V2/performance/performanceManage.jsp /accountBook/performance/v3/queryPerformance.do\n" +
            "src/main/webapp/WEB-INF/V2/tamPerformance/performanceManageNew.jsp          /tamanager/performance/queryPerformance.do\n" +
            "src/main/webapp/WEB-INF/V2/performance2017/performanceManage.jsp                无\n" +
            "src/main/webapp/WEB-INF/V2/performanceNew2017/courseConsumptionList.jsp             /accountBook/performance/v3/queryCourseConsumptionList.do\n" +
            "src/main/webapp/WEB-INF/V2/performanceNew2017/performanceManage.jsp                     /accountBook/performance/queryPerformance.do\n" +
            "src/main/webapp/WEB-INF/V2/performanceNew2017/performanceManage.jsp    /accountBook/performance/v3/queryPerformance.do\n" +
            "src/main/webapp/WEB-INF/V2/tadPerformance/performanceManage.jsp                     无\n" +
            "src/main/webapp/WEB-INF/V2/tamPerformance/dailyTarget/teamDailyTargetEdit.jsp               /tamanager/performance/teamDailyTargetEdit.do\n" +
            "src/main/webapp/WEB-INF/V2/tamPerformance/performanceManageNew.jsp              /tamanager/performance/queryPerformance.do\n" +
            "src/main/webapp/WEB-INF/mailbox/schoolMasterMailBox.jsp                         /mailBox/schoolMasterMailBox.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonFormalVideoManage.jsp                                      /addressBook/liveLesson/moreLiveLessonVideoManage.do\n" +
            "src/main/webapp/WEB-INF/V2/coursemonitor/courseMonitorManager.jsp                                                   /courseMonitor/courseBehaviourMonitor/toCourseMonitorManager.do\n" +
            "src/main/webapp/WEB-INF/V2/trialLecture/lectureTaskConfig/lectureTaskConfigPage.jsp                             /trialLecture/lectureTask/toLectureTaskConfigPage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/lectureAuditManager.jsp                                       /addressBook/lectureAudit/addressBook/lectureinvite/lectureAuditManager.jsp\n" +
            "src/main/webapp/WEB-INF/V2/trialLecture/teachingTask/teachingTaskManager.jsp                                /trialLecture/teachingTask/toTeachingTaskManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/lectureInviteManager.jsp                                      /addressBook/lectureInvite/toLectureInviteManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/myOnlineLectureInviteManager.jsp                          /addressBook/lectureInvite/toMyOnlineLectureInviteManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/lectureinvite/onlineLectureInviteManager.jsp                            /addressBook/lectureInvite/toOnlineLectureInviteManager.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonFormalVideoManage.jsp                                  /addressBook/liveLesson/moreLiveLessonVideoManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonVideoManage.jsp                            /addressBook/liveLesson/liveLessonVideoManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/myOnlineGroupLessonManage.jsp                 /addressBook/onlineGroupLesson/myOnlineGroupLessonManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/onlineGroupLessonManage.jsp               /addressBook/onlineGroupLesson/onlineGroupLessonManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherList.jsp                             /addressBook/searchTeacher/searchTeacher.do\n" +
            "src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherManage.jsp                           無\n" +
            "src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherV2Manage.jsp                     /addressBook/searchTeacher/toSearchTeacherManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherV2Manage.jsp    /addressBook/searchTeacher/toSearchTeacherManageWithDemand.do\n" +
            "src/main/webapp/WEB-INF/addressBook/teachingtask/teachingTaskManager.jsp                        無\n" +
            "src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherV2Manage.jsp                                     /addressBook/searchTeacher/toSearchTeacherManage.do\n" +
            "src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherV2Manage.jsp   /addressBook/searchTeacher/toSearchTeacherManageWithDemand.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/lectureinvite/lectureAuditManager.jsp                                          /addressBook/lectureAudit/addressBook/lectureinvite/lectureAuditManager.jsp\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/lectureinvite/lectureAuditManager.jsp                              /addressBook/lectureAudit/addressBook/lectureinvite/lectureAuditManager.jsp\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonFormalVideoManage.jsp                      /addressBook/liveLesson/moreLiveLessonVideoManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonUnFormalVideoManage.jsp               /addressBook/liveLesson/moreUnLiveLessonVideoManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/liveLesson/liveLessonVideoManage.jsp                   /addressBook/liveLesson/liveLessonVideoManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/livecloudLessonManager.jsp                   /addressBook/onlineGroupLesson/toLiveCloudLessonManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/myOnlineGroupLessonManage.jsp                    /addressBook/onlineGroupLesson/myOnlineGroupLessonManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/onlineGroupLessonManage.jsp                  /addressBook/onlineGroupLesson/onlineGroupLessonManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherManage.jsp                                      无\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherV2Manage.jsp                        /addressBook/searchTeacher/toSearchTeacherManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherV2Manage.jsp    /addressBook/searchTeacher/toSearchTeacherManageWithDemand.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/addStudentPoolChoose.jsp                             /addressBook/studentPoolV2/toStudentPoolChoose.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/enrollTeacherStudentPool.jsp                                 /addressBook/studentPoolV2/toEnrollTeacherStudentPool.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/enrollTeacherStudentPool.jsp     /addressBook/studentPoolV2/toEnrollTeacherStudentPoolWarn.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/myTeacherEnrollStudentPoolManage.jsp                     无\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/queryTeacherEnrollStudentPoolManage.jsp                          /addressBook/studentPoolV2/toQueryTeacherEnrollStudentPoolList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/reAddStudentPool.jsp                                 /addressBook/studentPoolV2/toReAddStudentPool.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/reAddStudentPoolFromStudentSent.jsp                          /addressBook/studentPoolV2/toReAddStudentPoolFromStudentSent.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/receiverStudentPoolAcceptManage.jsp                          /addressBook/studentPoolV2/receiverStudentPoolManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/receiverStudentPoolManage.jsp                                        /addressBook/studentPoolV2/toReceiverStudentPoolManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/recommendEnrollTeacher.jsp                                       /addressBook/studentPoolV2/showRecommendTeacherDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentPoolAcceptDetail.jsp                              /addressBook/studentPoolV2/showReceiverTeacherDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentPoolAcceptManage.jsp              无\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentPoolAcceptManageV2.jsp    无\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentPoolDetail.jsp    /addressBook/studentPoolV2/studentPoolDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentPoolManage.jsp                   無\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentSentStudentPoolManage.jsp         無\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/traStudentPoolManage.jsp             /addressBook/studentPoolV2/traStudentPoolManage.do\n" +
            "src/main/webapp/WEB-INF/tadStat/finishClassNewOrderManage/resetNewOrder.jsp                             /tad/finishClassNewOrder/toResetNewOrder.do\n" +
            "src/main/webapp/WEB-INF/tadStat/performanceTarget/performanceTarget.jsp                                             /tad/performance/toSetPerformanceTarget.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editMyTeacher.jsp                            /addressBook/toEditMyTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/cWEB-INF/addressBook/myTeacher/editMyTeacher.jsp                    /addressBook/toEditMyTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/courseContentPackageApplyManage.jsp    /tra/courseContentPackage/courseContentPackageApplyManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/editCourseContentPackage.jsp               /tra/courseContentPackage/toEditContentPackage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/editOutline.jsp                            /tra/courseContentPackage/outlineList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/flagPayedMain.jsp                              /tra/courseContentPackage/toFlagPayedMain.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/flagUnpayedMain.jsp                        /tra/courseContentPackage/toUnFlagPayedMain.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/toEditOutline.jsp                  /tra/courseContentPackage/toEditOutline.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/verifyCourseContentPackage.jsp                 /tra/courseContentPackage/toVerifyContentPackage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/verifyOfficialCourseContentPackage.jsp     /tra/courseContentPackage/toVerifyContentPackage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/viewOutline.jsp                    /tra/courseContentPackage/viewOutline.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/orderCourseList.jsp                         /crCalendar/crStudentOrderCourseList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/orderCourseList.jsp          /crCalendar/crTeacherRelatedBindingStudentOrderCourseList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/orderCourseList.jsp          /course/queryOrderCourseListOfAdjust.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/orderCourseList.jsp          /course/orderCourseShareRate.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/orderCourseList.jsp          /course/orderCourseList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/orderCourseList.jsp          /course/orderCourseListForTask.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/courseInformation/CrCourseInformation.jsp              /crCustomer/toCourseInformationManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/fourinone/allTypeCourseList.jsp           /customerFourInOne/toAllTypeCourseList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/fourinone/courseListPage.jsp                      /customerFourInOne/getCourseListPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/ts/courseConfirm/courseConfirmTaskDetailManager.jsp                /ts/courseConfirm/toCustomerOrderCourseConfirmDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/configCityTaskMain.jsp                /workPlatform/toConfigCityTaskMainPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/toConfigCityTask.jsp              /workPlatform/configCityTaskMainPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/batchSetStudentInfo.jsp                     /tad/sendOrder/toBatchSetStudentInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/batchSetStudentInfoV2.jsp                  /tad/sendOrder/accurate_distribute/toBatchSetStudentInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/seaSendOrderConfigList.jsp                 /tad/sendOrder/seaSendOrderConfigList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/setStudentInfo.jsp                 /tad/sendOrder/toSetStudentInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/setStudentInfoV2.jsp               /tad/sendOrder/accurate_distribute/toSetStudentInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/taNewSendOrderList.jsp             /tad/sendOrder/newTASendOrderList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/taNewSendOrderList.jsp /tad/sendOrder/newTASendOrderList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/taSendOrderList.jsp                            /tamanager/sendOrder/TASendOrderList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/taSendOrderList.jsp   /tad/sendOrder/TASendOrderList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/taSendOrderList.jsp  /tad/sendOrder/TASendOrderList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/taSendOrder/taSendOrderManager.jsp                        /tad/sendOrder/toTaOrderSetting.do\n" +
            "src/main/webapp/WEB-INF/tmkcityleads/addCommunicationPage.jsp                           /cityLeads/toAddCommunicationPage.do\n" +
            "src/main/webapp/WEB-INF/tmkcityleads/cityTmkExemptionManager.jsp                        /cityLeads/toCityTmkExemptionManager.do\n" +
            "src/main/webapp/WEB-INF/tmkcityleads/tmkCityLeadsManager.jsp                        /cityLeads/toOldTmkCityLeadsManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/accountBook/performance/performanceList.jsp                            无\n" +
            "ta-admin/src/main/webapp/WEB-INF/accountBook/performance/queryPerformance.jsp                                           无\n" +
            "ta-admin/src/main/webapp/WEB-INF/accountBook/teacherAssess/TeacherRecommendList.jsp                 /accountBook/teacherRecommend/toNewOrderTeacherRecommendList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/accountBook/teacherAssess/TeacherRecommendManager.jsp              /accountBook/teacherRecommend/toNewOrderTeacherRecommend.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/accountBook/teacherAssess/UpdateTeacherRecommend.jsp                       /accountBook/teacherRecommend/toUpdateTeacherRecommend.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/addOrderData.jsp                               /course/loadDataForAddOrder.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/addOrderData.jsp  /course/loadDataForAddOrderV2.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp                           /addressBook/toStudentPoolAddOrderV2.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp   /addressBook/toBindedStudentAddOrderV2.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/addOrderForBindedStudent.jsp   /addressBook/toBindedStudentAddOrder.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/addOrderTeacher.jsp                                /addressBook/preQueryOrderTeacherList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindApplyInfo.jsp                              /addressBook/applyForChangeBindInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindedStudentDetail.jsp                                /addressBook/toBindedStudentDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindedStudentList.jsp                      無\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindedStudentRelatedInfo.jsp               /addressBook/selectBindedStudentAssistantRelatedInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindedStuTRList.jsp                       /addressBook/queryBindedStuTRList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindingApplyList.jsp                               /addressBook/queryBindingTeacherApply.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/bindingTeacher.jsp                                         /addressBook/toQueryBindTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/courseTable.jsp                                                     /addressBook/toCourseTable.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/courseTimeManager.jsp                              /addressBook/toCourseTimeManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/recommendTeacher.jsp                                               /addressBook/toRecommendTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/recommendTeacherList.jsp                           /addressBook/getRecommendTeacherList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/selectStudentForAddOrder.jsp                   /course/toSelectStudentForAddOrder.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/setShareRate.jsp                   /addressBook/toSetShareRate.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentQuery.jsp                           K20181127 废弃使用\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/tadVerifyCustomerRebindApply.jsp                   /customer/toVerifyCustomerRebind.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/teacherInfo.jsp                    /addressBook/toEditTeacherInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/teacherLeads.jsp                                                       无\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/teacherLeadsList.jsp                       /addressBook/teacherLeads/queryTeacherLeads.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/teacherLeadsPage.jsp                       /addressBook/teacherLeads/toQueryTeacherLeads.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/toCustomerRebindApplyList.jsp    /customer/toViewRebindApplyList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/toTadCustomerRebindApplyList.jsp                        /customer/toTadCustomerRebindApplyList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/customerReport/customerStatus/onlyViewTaCustomerList.jsp           /customerReport/customerStatus/onlyViewTaCustomerList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/lectureinvite/onlineLectureInviteManager.jsp                   /addressBook/lectureInvite/toOnlineLectureInviteManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/lectureinvite/searchLectureAuditList.jsp                               /addressBook/lectureAudit/queryLectureAuditList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/lectureinvite/searchLectureInviteList.jsp                                      /addressBook/lectureInvite/queryLectureInviteList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/addTeacherCourse.jsp                     /addressBook/toAddTeacherCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/addTeacherGroupCourse.jsp                    /addressBook/toAddTeacherGroupCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/deteleTeacherCourse.jsp          /addressBook/toDeteleTeacherCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/deteleTeacherGroupCourse.jsp             /addressBook/toDeteleTeacherGroupCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editMyTeacher.jsp                        /addressBook/toEditMyTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editOfficialCourseContentPrice.jsp                   /addressBook/toEditOfficialCourseContentPrice.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editTeacherCourse.jsp                    /addressBook/toEditTeacherCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editTeacherGroupCourse.jsp               /addressBook/toEditTeacherGroupCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editTeacherStudies.jsp                           /addressBook/toEditTeacherStudies.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/editTeachingDistrict.jsp                         /addressBook/toEditTeachingDistrict.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/myTeacherManager.jsp                                                 /addressBook/toAddressBook.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/offShelfCourseContentConfirm.jsp                 /tra/courseContentPackage/toCloseSelfDefineCoursePackage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/publishCourseContentConfirm.jsp                  /tra/courseContentPackage/toPublishSelfDefineCoursePackage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherInfoQuality.jsp                   /addressBook/toTeacherInfoQuality.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherOptions.jsp                   /addressBook/teacherOptions.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherResponseRateList.jsp              /addressBook/teacherInfoResponseRateList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/applyTeacherAppointment.jsp                          /addressBook/toApplyInterviewMyTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/changeTeacherAppointmentInfo.jsp                             /addressBook/toChangeTeacherAppointmentInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/commonEditTeacherCommunicate.jsp         /addressBook/toAddCommunicate.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/commonEditTeacherCommunicate.jsp  /addressBook/toTeacherLeadsAddCommunicate.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/editTeacherCommunicate.jsp                   /addressBook/toCommunicateMyTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/operateTeacherAppointment.jsp                /addressBook/toOperateTeacherAppointment.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/queryRetreatFromClassInfoList.jsp                    /addressBook/queryRetreatFromClassInfoList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/showOptionsCourse.jsp                    /addressBook/showOptionsCourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/TeacherTimetable.jsp                 /addressBook/queryTeacherTimetable.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/communicate/teachStudentHistoryList.jsp                  /addressBook/toTeachStudentHistoryList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/evaluate/teacherEvaluateHistoryShow.jsp                      /addressBook/toAddTeacherEvaluate.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/evaluate/teacherEvaluateHistoryShow.jsp     /addressBook/toTeacherEvaluateHistoryShow.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/graduateCollege/editGraduateCollege.jsp                                  /addressBook/toEditGraduateCollege.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/graduateCollege/graduateCollegeList.jsp                                  /addressBook/getGraduateCollegeList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/graduateCollege/newGraduateCollege.jsp                                       /addressBook/toNewGraduateCollege.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/pastExperienceInfo/editPastExperienceInfo.jsp                                /addressBook/toEditPastExperienceInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/pastExperienceInfo/newPastExperienceInfo.jsp                                 addressBook/toNewPastExperienceInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/pastExperienceInfo/pastExperienceInfoList.jsp                        /addressBook/getPastExperienceInfoList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/praiseHonor/editPraiseHonor.jsp                      /addressBook/toEditPraiseHonor.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/praiseHonor/newPraiseHonor.jsp               /addressBook/toNewPraiseHonor.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/praiseHonor/praiseHonorList.jsp                 /addressBook/getPraiseHonorList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/successCase/editSuccessCase.jsp          /addressBook/toEditSuccessCase.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/successCase/newSuccessCase.jsp           /addressBook/toNewSuccessCase.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/successCase/successCaseList.jsp              /addressBook/getTeacherSuccessCaseList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherCourseInfoApply/editTeacherCourseApply.jsp                        /addressBook/toEditTeacherCourseInfoApply.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherCourseInfoApply/teacherCourseInfoApplyManage.jsp                       /addressBook/toTeacherCourseInfoApplyManege.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherInfo/editTeacherAddress.jsp                   /addressBook/toEditTeacherAddress.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherInfo/editTeacherHeadPic.jsp                           /addressBook/toEditTeacherHeadPic.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherInfo/editTeacherNick.jsp              /addressBook/toEditTeacherNick.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherInfo/editTeacherRealName.jsp              /addressBook/toEditTeacherRealName.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teacherInfo/editTeacherSchoolAge.jsp                     /addressBook/toEditTeacherSchoolAge.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teachFeatures/editTeachFeatures.jsp          /addressBook/toEditTeachFeatures.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/myTeacher/teachFeatures/newTeachFeatures.jsp               /addressBook/toNewTeachFeatures.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/createTestLiveCloudCourse.jsp                                /addressBook/onlineGroupLesson/toCreateTestLiveLesson.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/onlinegrouplesson/livecloudLessonList.jsp                          /addressBook/onlineGroupLesson/queryStudentOnlineInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/queryTeacher/queryTeacherManage.jsp                                            addressBook/toQueryTeacherManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/recommendTeacher.jsp                                         /addressBook/searchTeacher/toRecommendTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/searchTeacherList.jsp                        /addressBook/searchTeacher/searchTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/setStrictSelectionTeacherTimePage.jsp                                        /addressBook/searchTeacher/setTeacherTimePage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/setTeacherTimePage.jsp                                   /addressBook/searchTeacher/setTeacherTimePage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/searchTeacher/showTeacherTimeSet.jsp                               /addressBook/searchTeacher/showTeacherTime.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/addStudentPoolChoose.jsp                 /addressBook/studentPoolV2/toStudentPoolChoose.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/closeStudentPool.jsp                         /addressBook/studentPoolV2/toCloseStudentPool.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/studentPoolV2/studentPoolAcceptList.jsp                    /addressBook/studentPoolV2/studentPoolAcceptList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/addressBook/teachingtask/teachingTaskList.jsp                                                     无\n" +
            "ta-admin/src/main/webapp/WEB-INF/complaints/complaintsDetailInfo.jsp                        /complaints/toComplaintsDetailInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/complaints/complaintsDetailInfo.jsp       /complaints/toComplaitsDetailFromWorkPlatForm.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/continueCourse.jsp                                              无\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/setCourseTime.jsp                                                                       /course/toCourseTime.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/course/setCourseTimeList.jsp                                   /course/getTeacherCalenderV2.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/cr/mytask/crMyTaskList.jsp                                     /cr/mytask/queryCrMyTaskListTaskList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/customerInfoMaintain/changeNextConnectTime.jsp                             無\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/customerInfoMaintain/customerLostConfirm.jsp                  /customer/toCustomerLostConfirm.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/customerInfoMaintain/customerNotConnect.jsp               /customer/toCustomerNotConnect.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/customerInfoMaintain/customerPotential.jsp                        /customer/toCustomerPotential.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/customerInfoMaintain/editCustomerSpreadSourse.jsp                 /customer/toEditSpreadSourse.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/fourinone/courseListPage.jsp                                              /customerFourInOne/getCourseListPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/fourinone/customerCommunicateHistoryListV2.jsp                                /customerFourInOne/getCustomerCommunicateHistoryPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/fourinone/orderPage.jsp                                           /customerFourInOne/getOrderInfoPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/batchChangeBindApply.jsp                   /addressBook/batchApplyForChangeBindInfo.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/confirmCourseTime.jsp                              /crCustomer/confirmCourseTime.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/CrCustomerList.jsp                                 /crCustomer/queryMyCustomerList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/customerRemarkEdit.jsp                     /crCustomer/toCustomerEditRemark.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/customerRemarkEditForTag.jsp       /customer/toCustomerEditRemark.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/customerStatusOptions.jsp          /crCustomer/customerStatusOptions.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/errMsgList.jsp                 /addressBook/toErrMsgList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/myCustomerList.jsp                     无\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/myCustomerListForCustomerTag.jsp           /customer/queryMyCustomerList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/myCustomerListV2.jsp                           /customer/queryMyCustomerList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/myFastFollowCustomerList.jsp               /fastFollowCustomer/toFastFollowCustomerList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/customer/mycustomer/studyConsultantCustomerList.jsp                /studyConsultantCustomer/queryMyCustomerList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/huanxin/chatHistoryManage.jsp                                  /getHuanxinPws.do/chatHistoryManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/groupOrderInfoDetail.jsp                                 /groupOrder/queryOrderDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/groupOrderInfoList.jsp                               /groupOrder/orderInfoList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/liveClassOrderInfoDetail.jsp                             /liveClass/queryOrderDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/liveClassOrderInfoDetail.jsp /liveClass/queryOrderDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/liveClassOrderInfoList.jsp                                   无\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/orderInfoDetail.jsp                                  /order/queryOrderDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/orderInfoDetail.jsp  /tsOrderApply /toOrderInfoByOrderApply.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/order/orderInfoList.jsp                            /order/orderInfoList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/set/setupData.jsp                              /set/toSetupData.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/customerStatusConfig/configList.jsp        /tad/statusConfig/toConfigList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/customerStatusConfig/setStatusConfig.jsp               /tad/statusConfig/toSetStatusConfig.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/teacherCourseInfoApply/batchReviewTeacherCourseApply.jsp               /addressBook/toBatchVerify.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/teacherCourseInfoApply/batchReviewTeacherGroupCourseApply.jsp              /addressBook/toBatchVerifyGroup.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/addStudentCommunication.jsp                        /workPlatform/taskAddCommunication.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/addTeacherCommunication.jsp                            /workPlatform/taskAddCommunication.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/toTeamWorkTaskListForTad.jsp                                         /workPlatform/toTadTeamWorkTask.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/viewStudentCommunication.jsp                                   /workPlatform/viewTaskDetails.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tadStat/workPlatform/viewTeacherCommunication.jsp                                      /workPlatform/viewTaskDetails.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/assistantApplyChangebindingConfirm.jsp                       /tamanager/student/toChangebindingApplyConfirm.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/assistantApplyChangebindingManage.jsp                            /tamanager/student/assistantApplyChangebindingManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/assistantBatchApplyChangebindingConfirm.jsp              /tamanager/student/toBatchChangebindingApplyConfirm.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/batchDealTeacherBindingApply.jsp                             无\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/bindingTeacherApplyList.jsp                      无\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/bindingTeacherManager.jsp                                                             無\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/batchOperateStudent/batchOperateStudentManage.jsp            /tamanager/relation/toBatchOperateStudent.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/batchOperateTeacher/batchOperateTeacherManage.jsp                    無\n" +
            "ta-admin/src/main/webapp/WEB-INF/tamanager/taSendOrder/taSendOrderList.jsp                                  /tamanager/sendOrder/TASendOrderList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tc/allTheTeacher/tcTeacherManager.jsp                                              /tc/allTheTeacher/toTCTeacherManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tcsOnlineTechnicalHelp/communicateRecord/communicateRecordDialog.jsp               /onlineTechnicalHelp/helpDesk/getCommunicateRecordDialog.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tmkcityleads/LeadsQueryWithinBatchPage.jsp                                             /cityLeads/singleLeadsQueryPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/tmkcityleads/LeadsQueryWithinBatchPage.jsp   /cityLeads/leadsQueryWithinBatchPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/batchDealTeacherBindingApply.jsp                                   /tamanager/relation/toBatchDealTeacherBindingApply.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/bindingTeacherApplyList.jsp                            /tamanager/relation/queryBindingTeacherApply.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/bindingTeacherManager.jsp                              /tamanager/relation/toQueryBindTeacherApply.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/allTheTeacher/allTheTeacherManager.jsp                                         /tra/allTheTeacher/toAllTheTeacher.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/allTheTeacher/editOperationalAssessment.jsp                                             /tra/allTheTeacher/toEditOperationalAssessment.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/allTheTeacher/editUserLiveDevice.jsp                                   /tra/allTheTeacher/toEditUserLiveDevice.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/communityOperation/selectTeacherManage.jsp                             /tra/communityOperation/toSelectTeacherMainPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/interviewTeacher/exportInterviewTeacherList.jsp                        無\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/interviewTeacher/interviewTeacherList.jsp                      /tra/interview/interviewTeacherList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/traStat/interviewTeacher/interviewTeacherManage.jsp                                 /tra/interview/toInterviewTeacherManage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/addorder/preDegradeAppeal.jsp                           /addressBook/preDegradeAppeal.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/bigBackstageSales/adjustmentRefund.jsp              /bigBackstageSales/preAdjustment.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/bigBackstageSales/adjustmentReward.jsp                              /bigBackstageSales/preAdjustment.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/bigBackstageSales/cityTargetSetting.jsp                             /bigBackstageSales/toCityTargetSetting.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/bigBackstageSales/performanceTargetAdjustment.jsp                   /bigBackstageSales/toPerformanceTargetAdjustment.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/courseContentPackage/addSelfDefineCourseContentPackagePrice.jsp                                 /tra/courseContentPackage/toSetCourseContentPrice.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/customer/onlineStudentManager/monitorCourse.jsp                 /customer/onlineStudent/monitorCourseV1.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/customer/onlineStudentManager/monitorCourse.jsp     /customer/onlineStudent/monitorCourseV2.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/customer/onlineStudentManager/monitorCourseNew.jsp                  /customer/onlineStudent/monitorCourseV1.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/customer/onlineStudentManager/monitorCourseNew.jsp    /customer/onlineStudent/monitorCourseV2.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/customer/onlineStudentManager/onlineStudentList.jsp                         /customer/onlineStudent/queryOnlineStudentList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/favoriteTeacher/favoriteTeacherList.jsp                                     /addressBook/favoriteTeacher/queryFavoriteTeacherList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/login/login.jsp                         无\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/login/loginV2.jsp                       /login/logout.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/order/subOrderDetail.jsp                            /order/queryNewOrderDetail.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/order/subOrderDetailForClassHour.jsp                /order/queryNewOrderDetailForClassHour.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/publicSea/publicSeaApplyList.jsp                                    /publicSea/publicSeaApplyList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/trialLecture/teachingTask/randomDispatchPage.jsp                        /trialLecture/teachingTask/toRandomDistribution.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/trialLecture/teachingTask/teachingTaskList.jsp                                  /trialLecture/teachingTask/queryTeachingTask.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/voip/voipHistoryList.jsp                                                /voip/voipInfo/queryMyVoipHistoryList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/voip/voipHistoryNoPageList.jsp                                  /voip/voipInfo/queryMyVoipHistoryNoPageList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/voip/voipManagerTs.jsp                                                      /voip/voipInfo/voipManagerTs.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/voip/workPhoneCallHistoryPage.jsp                   /voip/voipInfo/getWorkPhoneCallHistoryPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V2/wallet/customerWalletDetailList.jsp                     /customer/wallet/queryCustomerWalletDetailList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V3/customerCommunicate/customerCommunicateManager.jsp                  /customer/customerCommunicate/toCustomerCommunicateManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V3/studentTeacher/voipTsCustomerCommunicateList.jsp                    /ts/tsCustomerVoipRelatedInfo/toCustomerCommunicateList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V3/studentTeacher/voipTsTeacherCommunicateRecordList.jsp                   /ts/tsTeacherVoipRelatedInfo/toTeacherCommunicateRecordList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V3/ta/firstCourse/firstCourseManagerQualityControl.jsp                         /firstCourseQc/toFirstCourseQualityControl.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V3/tsd/newrecruitslist/communicationHistory.jsp                        /intradayCommunicateInfo/communicationHistory.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/V3/tsd/newrecruitslist/newRecruitsVoipCommentsManager.jsp          /newRecruits/toNewRecruitsVoipCommentsManager.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/canCloseTaskList.jsp                                      /workPlatform/canCloseTaskList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/closeTaskRequest.jsp                              /workPlatform/closeTaskPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/delayTaskPageRequest.jsp                  /workPlatform/delayTaskPage.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/taCloseTaskDetailList.jsp                     /workPlatform/queryTaCloseTaskList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/taCloseTaskDetailList.jsp /workPlatform/viewTaWorkTask.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/taDealingOverTimeTaskList.jsp                             /workPlatform/queryTaDealingOverTimeTaskList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/taDealingOverTimeTaskList.jsp /workPlatform/viewTaWorkTask.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/taDelayTaskList.jsp                                                           /workPlatform/viewTaWorkTask.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/taDelayTaskList.jsp         /workPlatform/queryTaDelayTaskList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/workBenchCloseTaskList.jsp                            /workPlatform/queryTraCloseTaskList.do\n" +
            "ta-admin/src/main/webapp/WEB-INF/workPlatform/workBenchInformationTaskList.jsp                  /workPlatform/queryTraDealingOverTimeTaskList.do";

    public static void main(String[] args) throws IOException {
//        WriteJs.testString(layerJs);
        WriteJs.writeString("/js/layer/layer.js", layerJs);
    }

}
