dubbo:
  registry:
    address: zookeeper://localhost:2181
    username: leamem
    password: WhiteWinter
    simplified: true
  application:
    name: winter-provider
  config-center:
    address: zookeeper://localhost:2181

#    注册中心
    username: leamem
    password: WhiteWinter


  metadata-report:
    address: zookeeper://localhost:2181
  protocol:
    port: 9992
