spring:
  kafka:
    bootstrap-servers: 172.20.13.97:9092
    template:
      default-topic: dev_msg_detect_result_1

    listener:
      concurrency: 3

    producer:
      batch-size: 10
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


    consumer:
      group-id: test_consumer
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
      enable-auto-commit: true

  datasource:
    url: jdbc:mysql://leamem.tpddns.cn:3306/test?autoReconnect=true&autoCommit=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: CUIjin9874123?
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: WeCantStudyTogether
      connection-test-query: select 1

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

server:
  servlet:
    context-path: /midware

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 30
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lea.kumiko.midware.entity


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql