dubbo:
  application:
    name: consumers
  registry:
    address: zookeeper://192.168.40.13:2181
    username: leamem
    password: WhiteWinter
    check: false
  consumer:
    check: false

  metadata-report:
    address: zookeeper://192.168.40.13:2181

server:
  port: 9999
